### ISSUE TITLE
EPIC 1 Viewing and Navigation

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/boutique_ado_v1#1]
**Description:** Viewing and Navigation

**Details:**
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70364129) View a list of products
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70098555) View a specific category of products
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10?pane=issue&itemId=70105394) View individual product details
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70105449) Quickly identify deals, clearance items and special offers
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70109025) Easily view the total of my purchases at any time
